language: cpp
compiler:
  - gcc
  - clang
matrix:
  include:
    - python: "2.7"
      compiler: gcc
      env: SWIGLANG=python
    - jdk: oraclejdk6
      compiler: gcc
      env: SWIGLANG=java
    - jdk: oraclejdk7
      compiler: gcc
      env: SWIGLANG=java
    - perl: "5.10"
      compiler: gcc
      env: SWIGLANG=perl
    - rvm: 1.8.7
      compiler: gcc
      env: SWIGLANG=ruby
before_install:
  - sudo apt-get install libboost-dev -qq
script:
  - ./autogen.sh && ./configure
  - make -s
  - echo "SWIGLANG: $SWIGLANG"
#  - make -k check-$SWIGLANG-examples check-$SWIGLANG-test-suite
branches:
  only:
    - master
